# Generated by Django 5.2.17 on 2026-09-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_deal', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('NEW ARRIVAL', 'NEW ARRIVAL')], max_length=100)),
                ('sale', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('img', models.ImageField(default=None, null=True, upload_to='media/slider')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
